### ISSUE TITLE
Konfiguracja Jenkinsa

### ISSUE THREAD

**Issue by Blysku** [JA2018KATMM/Battleships#2]
Skonfigurowanie serwera pod Jenkinsa, postawienie i konfiguracja Jenkinsa, skonfigurowanie wymagań i skryptów.

**Comment by michalakadam** [comment]
Java 8 zainstalowana na serwerze Jenkinsowym.

**Comment by michalakadam** [comment]
Instalacja Mavena i Gita.

**Comment by matsyposz** [comment]
pierwszy pipeline stworzony, buduje się z naszego githuba - branch jenkins
